"""populate dummy data

Revision ID: fe3e3f1fbc2f
Revises: 95cee7a1fa55
Create Date: 2023-05-07 12:26:54.941126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3e3f1fbc2f'
down_revision = '95cee7a1fa55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # add email types
    op.execute("""
        INSERT INTO email_types (name) 
        VALUES 
            ('Auto email 1'),
            ('Auto email 2'),
            ('Auto email 3'),
            ('Auto email 4'),
            ('Auto email 5'),
            ('Auto email 6'),
            ('Auto email 7'),
            ('Auto email 8'),
            ('Auto email 9'),
            ('Auto email 10');
        """)

        # add users
    op.execute("""
        INSERT INTO users (
            ghr_id,
            first_name,
            last_name,
            dept_name,
            status,
            title,
            email,
            hashed_pw,
            subscribed) 
        VALUES 
            ('11111111', 'John', 'Smith', 'dept1', 'active', 'title', 'john@example.com', 'password', 1),
            ('22222222', 'Jane', 'Doe', 'dept2', 'active', 'title', 'jane@example.com', 'password', 1),
            ('33333333', 'douche', 'bag', 'dept3', 'active', 'title', 'douche@example.com', 'password', 1),
            ('44444444', 'Flim', 'Flam', 'dept4', 'active', 'title', 'flim@example.com', 'password', 1),
            ('55555555', 'Bob', 'Johnson', 'dept4', 'active', 'title', 'bob@example.com', 'password', 1);
        """)
    
    # associate users with emails types
    op.execute("""
        INSERT INTO user_email_types (user_id, email_type_id) 
        VALUES 
            (1, 1),
            (1, 2),
            (1, 3),
            (1, 4),
            (1, 5),

            (2, 6),
            (2, 7),
            (2, 8),
            (2, 9),
            (2, 10),

            (3, 1),
            (3, 2),
            (3, 3),
            (3, 4),
            (3, 5),

            (4, 6),
            (4, 7),
            (4, 8),
            (4, 9),
            (4, 10),

            (5, 1),
            (5, 2),
            (5, 3),
            (5, 4),
            (5, 5);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
