"""populate dummy data

Revision ID: 9ff2c5b24efa
Revises: ac548a1becae
Create Date: 2023-04-30 13:26:32.475125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from app.models.models import Item, EmailType, User, UserEmailType
from app.database import SessionLocal


# revision identifiers, used by Alembic.
revision = '9ff2c5b24efa'
down_revision = 'ac548a1becae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # add email types
    op.execute("""
        INSERT INTO email_types (name) 
        VALUES 
            ('Auto email 1'),
            ('Auto email 2'),
            ('Auto email 3'),
            ('Auto email 4'),
            ('Auto email 5'),
            ('Auto email 6'),
            ('Auto email 7'),
            ('Auto email 8'),
            ('Auto email 9'),
            ('Auto email 10');
        """)

        # add users
    op.execute("""
        INSERT INTO users (name, email, subscribed) 
        VALUES 
            ('John Smith', 'john@example.com', 1),
            ('Jane Doe', 'jane@example.com', 1),
            ('Douche Bag', 'douche@example.com', 1),
            ('Flim Flam', 'flim@example.com', 1),
            ('Bob Johnson', 'bob@example.com', 1);
        """)
    
    # associate users with emails types
    op.execute("""
        INSERT INTO user_email_types (user_id, email_type_id) 
        VALUES 
            (1, 1),
            (1, 2),
            (1, 3),
            (1, 4),
            (1, 5),

            (2, 6),
            (2, 7),
            (2, 8),
            (2, 9),
            (2, 10),

            (3, 1),
            (3, 2),
            (3, 3),
            (3, 4),
            (3, 5),

            (4, 6),
            (4, 7),
            (4, 8),
            (4, 9),
            (4, 10),

            (5, 1),
            (5, 2),
            (5, 3),
            (5, 4),
            (5, 5);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
